import React from 'react';
import './DynamicGrid.module.css'; // Import CSS module for specific styles

// Define an array of emojis with descriptions
const emojiList = [
    { emoji: "😀", description: "Grinning Face" },
    { emoji: "😃", description: "Grinning Face with Big Eyes" },
    { emoji: "😄", description: "Grinning Face with Smiling Eyes" },
    { emoji: "😁", description: "Beaming Face with Smiling Eyes" },
    { emoji: "😆", description: "Grinning Squinting Face" },
    { emoji: "😅", description: "Grinning Face with Sweat" },
    { emoji: "😂", description: "Face with Tears of Joy" },
    { emoji: "🤣", description: "Rolling on the Floor Laughing" },
    { emoji: "😊", description: "Smiling Face with Smiling Eyes" },
    { emoji: "😇", description: "Smiling Face with Halo" },
    { emoji: "🙂", description: "Slightly Smiling Face" },
    { emoji: "🙃", description: "Upside-Down Face" },
    { emoji: "😉", description: "Winking Face" },
    { emoji: "😌", description: "Relieved Face" },
    { emoji: "😍", description: "Smiling Face with Heart-Eyes" },
    { emoji: "🥰", description: "Smiling Face with Hearts" },
    { emoji: "😘", description: "Face Blowing a Kiss" },
    { emoji: "😗", description: "Kissing Face" },
    { emoji: "😙", description: "Kissing Face with Smiling Eyes" },
    { emoji: "😚", description: "Kissing Face with Closed Eyes" },
    { emoji: "😋", description: "Face Savoring Food" },
    { emoji: "😛", description: "Face with Tongue" },
    { emoji: "😜", description: "Winking Face with Tongue" },
    { emoji: "🤪", description: "Zany Face" },
    { emoji: "😝", description: "Squinting Face with Tongue" },
    { emoji: "🤑", description: "Money-Mouth Face" },
    { emoji: "🤗", description: "Hugging Face" },
    { emoji: "🤭", description: "Face with Hand Over Mouth" },
    { emoji: "🤫", description: "Shushing Face" },
    { emoji: "🤔", description: "Thinking Face" },
    { emoji: "🤐", description: "Zipper-Mouth Face" },
    { emoji: "🤨", description: "Face with Raised Eyebrow" },
    { emoji: "😐", description: "Neutral Face" },
    { emoji: "😑", description: "Expressionless Face" },
    { emoji: "😶", description: "Face Without Mouth" },
    { emoji: "😏", description: "Smirking Face" },
    { emoji: "😒", description: "Unamused Face" },
    { emoji: "🙄", description: "Face with Rolling Eyes" },
    { emoji: "😬", description: "Grimacing Face" },
    { emoji: "🤥", description: "Lying Face" },
    { emoji: "😔", description: "Pensive Face" },
    { emoji: "😪", description: "Sleepy Face" },
    { emoji: "🤤", description: "Drooling Face" },
    { emoji: "😴", description: "Sleeping Face" },
    { emoji: "😷", description: "Face with Medical Mask" },
    { emoji: "🤒", description: "Face with Thermometer" },
    { emoji: "🤕", description: "Face with Head-Bandage" },
    { emoji: "🤢", description: "Nauseated Face" },
    { emoji: "🤮", description: "Face Vomiting" },
    { emoji: "🤧", description: "Sneezing Face" },
    { emoji: "🥵", description: "Hot Face" },
    { emoji: "🥶", description: "Cold Face" },
    { emoji: "🥴", description: "Woozy Face" },
    { emoji: "😵", description: "Dizzy Face" },
    { emoji: "🤯", description: "Exploding Head" },
    { emoji: "🤠", description: "Cowboy Hat Face" },
    { emoji: "🥳", description: "Partying Face" },
    { emoji: "😎", description: "Smiling Face with Sunglasses" },
    { emoji: "🤓", description: "Nerd Face" },
    { emoji: "🧐", description: "Face with Monocle" },
    { emoji: "😕", description: "Confused Face" },
    { emoji: "😟", description: "Worried Face" },
    { emoji: "🙁", description: "Slightly Frowning Face" },
    { emoji: "☹️", description: "Frowning Face" },
    { emoji: "😮", description: "Face with Open Mouth" },
    { emoji: "😯", description: "Hushed Face" },
    { emoji: "😲", description: "Astonished Face" },
    { emoji: "😳", description: "Flushed Face" },
    { emoji: "🥺", description: "Pleading Face" },
    { emoji: "😦", description: "Frowning Face with Open Mouth" },
    { emoji: "😧", description: "Anguished Face" },
    { emoji: "😨", description: "Fearful Face" },
    { emoji: "😰", description: "Anxious Face with Sweat" },
    { emoji: "😥", description: "Sad but Relieved Face" },
    { emoji: "😢", description: "Crying Face" },
    { emoji: "😭", description: "Loudly Crying Face" },
    { emoji: "😱", description: "Face Screaming in Fear" },
    { emoji: "😖", description: "Confounded Face" },
    { emoji: "😣", description: "Persevering Face" },
    { emoji: "😞", description: "Disappointed Face" },
    { emoji: "😓", description: "Downcast Face with Sweat" },
    { emoji: "😩", description: "Weary Face" },
    { emoji: "😫", description: "Tired Face" },
    { emoji: "🥱", description: "Yawning Face" },
    { emoji: "😤", description: "Face with Steam From Nose" },
    { emoji: "😡", description: "Pouting Face" },
    { emoji: "😠", description: "Angry Face" },
    { emoji: "🤬", description: "Face with Symbols on Mouth" },
    { emoji: "😈", description: "Smiling Face with Horns" },
    { emoji: "👿", description: "Angry Face with Horns" },
    { emoji: "💀", description: "Skull" },
    { emoji: "☠️", description: "Skull and Crossbones" },
    { emoji: "💩", description: "Pile of Poo" },
    { emoji: "🤡", description: "Clown Face" },
    { emoji: "👹", description: "Ogre" },
    { emoji: "👺", description: "Goblin" },
    { emoji: "👻", description: "Ghost" },
    { emoji: "👽", description: "Alien" },
    { emoji: "👾", description: "Alien Monster" },
    { emoji: "🤖", description: "Robot" },
    { emoji: "😺", description: "Grinning Cat" },
    { emoji: "😸", description: "Grinning Cat with Smiling Eyes" },
    { emoji: "😹", description: "Cat with Tears of Joy" },
    { emoji: "😻", description: "Smiling Cat with Heart-Eyes" },
    { emoji: "😼", description: "Cat with Wry Smile" },
    { emoji: "😽", description: "Kissing Cat" },
    { emoji: "🙀", description: "Weary Cat" },
    { emoji: "😿", description: "Crying Cat" },
    { emoji: "😾", description: "Pouting Cat" },
    { emoji: "💋", description: "Kiss Mark" },
    { emoji: "👋", description: "Waving Hand" },
    { emoji: "🤚", description: "Raised Back of Hand" },
    { emoji: "🖐️", description: "Hand with Fingers Splayed" },
    { emoji: "✋", description: "Raised Hand" },
    { emoji: "🖖", description: "Vulcan Salute" },
    { emoji: "👌", description: "OK Hand" },
    { emoji: "🤌", description: "Pinched Fingers" },
    { emoji: "🤏", description: "Pinching Hand" },
    { emoji: "✌️", description: "Victory Hand" },
    { emoji: "🤞", description: "Crossed Fingers" },
    { emoji: "🤟", description: "Love-You Gesture" },
    { emoji: "🤘", description: "Sign of the Horns" },
    { emoji: "🤙", description: "Call Me Hand" },
    { emoji: "👈", description: "Backhand Index Pointing Left" },
    { emoji: "👉", description: "Backhand Index Pointing Right" },
    { emoji: "👆", description: "Backhand Index Pointing Up" },
    { emoji: "👇", description: "Backhand Index Pointing Down" },
    { emoji: "☝️", description: "Index Pointing Up" },
    { emoji: "👍", description: "Thumbs Up" },
    { emoji: "👎", description: "Thumbs Down" },
    { emoji: "✊", description: "Raised Fist" },
    { emoji: "👊", description: "Fist Bump" },
    { emoji: "🤛", description: "Left-Facing Fist" },
    { emoji: "🤜", description: "Right-Facing Fist" },
    { emoji: "👏", description: "Clapping Hands" },
    { emoji: "🙌", description: "Raising Hands" },
    { emoji: "👐", description: "Open Hands" },
    { emoji: "🤝", description: "Handshake" },
    { emoji: "🙏", description: "Folded Hands" },
    { emoji: "✍️", description: "Writing Hand" },
    { emoji: "💅", description: "Nail Polish" },
    { emoji: "👁️", description: "Eye" },
    { emoji: "👀", description: "Eyes" },
    { emoji: "🧠", description: "Brain" },
    { emoji: "🦷", description: "Tooth" },
    { emoji: "🦴", description: "Bone" },
    { emoji: "👅", description: "Tongue" },
    { emoji: "👄", description: "Mouth" },
    { emoji: "💖", description: "Sparkling Heart" },
    { emoji: "💔", description: "Broken Heart" },
    { emoji: "❤️", description: "Red Heart" },
    { emoji: "🧡", description: "Orange Heart" },
    { emoji: "💛", description: "Yellow Heart" },
    { emoji: "💚", description: "Green Heart" },
    { emoji: "💙", description: "Blue Heart" },
    { emoji: "💜", description: "Purple Heart" },
    { emoji: "🤎", description: "Brown Heart" },
    { emoji: "🖤", description: "Black Heart" },
    { emoji: "💝", description: "Heart with Ribbon" },
    { emoji: "💗", description: "Growing Heart" },
    { emoji: "💓", description: "Beating Heart" },
    { emoji: "💞", description: "Revolving Hearts" },
    { emoji: "💕", description: "Two Hearts" },
    { emoji: "💌", description: "Love Letter" },
    { emoji: "💋", description: "Kiss Mark" },
    { emoji: "💏", description: "Kiss" },
    { emoji: "💑", description: "Couple with Heart" },
    { emoji: "👩‍❤️‍👨", description: "Woman and Man Holding Hands" },
    { emoji: "👩‍❤️‍👩", description: "Woman and Woman Holding Hands" },
    { emoji: "👨‍❤️‍👨", description: "Man and Man Holding Hands" },
    { emoji: "👨‍👩‍👧", description: "Family: Man, Woman, Girl" },
    { emoji: "👨‍👩‍👦", description: "Family: Man, Woman, Boy" },
    { emoji: "👨‍👩‍👧‍👦", description: "Family: Man, Woman, Girl, Boy" },
    { emoji: "👨‍👩‍👧‍👧", description: "Family: Man, Woman, Girls" },
    { emoji: "👨‍👩‍👦‍👦", description: "Family: Man, Woman, Boys" },
    { emoji: "👨‍👩‍👦‍👧", description: "Family: Man, Woman, Boy, Girl" },
    { emoji: "👩‍👧", description: "Woman and Girl" },
    { emoji: "👩‍👦", description: "Woman and Boy" },
    { emoji: "👩‍👧‍👦", description: "Woman, Girl, Boy" },
    { emoji: "👩‍👧‍👧", description: "Woman and Girls" },
    { emoji: "👩‍👦‍👦", description: "Woman and Boys" },
    { emoji: "👩‍👦‍👧", description: "Woman, Boy, Girl" },
    { emoji: "👨‍👧", description: "Man and Girl" },
    { emoji: "👨‍👦", description: "Man and Boy" },
    { emoji: "👨‍👧‍👦", description: "Man, Girl, Boy" },
    { emoji: "👨‍👧‍👧", description: "Man and Girls" },
    { emoji: "👨‍👦‍👦", description: "Man and Boys" },
    { emoji: "👨‍👦‍👧", description: "Man, Boy, Girl" },
    { emoji: "👩‍❤️‍💋‍👨", description: "Kiss: Woman and Man" },
    { emoji: "👩‍❤️‍💋‍👩", description: "Kiss: Woman and Woman" },
    { emoji: "👨‍❤️‍💋‍👨", description: "Kiss: Man and Man" },
    { emoji: "👩‍❤️‍👨", description: "Couple with Heart: Woman and Man" },
    { emoji: "👩‍❤️‍👩", description: "Couple with Heart: Woman and Woman" },
    { emoji: "👨‍❤️‍👨", description: "Couple with Heart: Man and Man" },
    { emoji: "💞", description: "Revolving Hearts" },
    { emoji: "💓", description: "Beating Heart" },
    { emoji: "💗", description: "Growing Heart" },
    { emoji: "💝", description: "Heart with Ribbon" },
    { emoji: "💌", description: "Love Letter" },
    { emoji: "💭", description: "Thought Balloon" },
    { emoji: "🌈", description: "Rainbow" },
    { emoji: "🌞", description: "Sun with Face" },
    { emoji: "🌜", description: "Moon with Face" },
    { emoji: "🌚", description: "New Moon Face" },
    { emoji: "🌕", description: "Full Moon" },
    { emoji: "🌟", description: "Glowing Star" },
    { emoji: "⭐", description: "Star" },
    { emoji: "✨", description: "Sparkles" },
    { emoji: "🌠", description: "Shooting Star" },
    { emoji: "🌌", description: "Milky Way" },
    { emoji: "🌊", description: "Water Wave" },
    { emoji: "💧", description: "Droplet" },
    { emoji: "🌧️", description: "Cloud with Rain" },
    { emoji: "⛈️", description: "Cloud with Lightning and Rain" },
    { emoji: "🌩️", description: "Cloud with Lightning" },
    { emoji: "🌫️", description: "Fog" },
    { emoji: "🌪️", description: "Tornado" },
    { emoji: "🌈", description: "Rainbow" },
    { emoji: "🌞", description: "Sun with Face" },
    { emoji: "🌙", description: "Moon" },
    { emoji: "🌜", description: "Moon with Face" },
    { emoji: "🌓", description: "First Quarter Moon" },
    { emoji: "🌑", description: "New Moon" },
    { emoji: "🌕", description: "Full Moon" },
    { emoji: "🌖", description: "Waning Gibbous Moon" },
    { emoji: "🌗", description: "Last Quarter Moon" },
    { emoji: "🌘", description: "Waning Crescent Moon" },
    { emoji: "🌚", description: "New Moon Face" },
    { emoji: "🌝", description: "Full Moon Face" },
    { emoji: "🌞", description: "Sun with Face" },
    { emoji: "☀️", description: "Sun" },
    { emoji: "🌤️", description: "Sun Behind Small Cloud" },
];

const DynamicGrid: React.FC = () => {
  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '10px' }}>
        {emojiList.map((item, index) => (
          <div key={index} className="emoji-card p-4 border rounded text-center bg-light hover-effect">
            <div style={{ display:'flex', alignItems: 'flex-end', height:'15px', width:'15px'  }}>
              <img src="/bookmark.png" alt="" />
            </div>
            <div className="emoji" style={{ fontSize: '2rem' }}>{item.emoji}</div>
            <div className="description mt-2">{item.description}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DynamicGrid;
