import React from 'react'
const emojiList = [
    { emoji: '🍏', description: 'Green Apple' },
    { emoji: '🍎', description: 'Red Apple' },
    { emoji: '🍐', description: 'Pear' },
    { emoji: '🍊', description: 'Tangerine' },
    { emoji: '🍋', description: 'Lemon' },
    { emoji: '🍌', description: 'Banana' },
    { emoji: '🍉', description: 'Watermelon' },
    { emoji: '🍇', description: 'Grapes' },
    { emoji: '🍓', description: 'Strawberry' },
    { emoji: '🫐', description: 'Blueberry' },
    { emoji: '🥭', description: 'Mango' },
    { emoji: '🍍', description: 'Pineapple' },
    { emoji: '🥥', description: 'Coconut' },
    { emoji: '🥝', description: 'Kiwi Fruit' },
    { emoji: '🍅', description: 'Tomato' },
    { emoji: '🍆', description: 'Eggplant' },
    { emoji: '🥔', description: 'Potato' },
    { emoji: '🥕', description: 'Carrot' },
    { emoji: '🌽', description: 'Ear of Corn' },
    { emoji: '🌶️', description: 'Hot Pepper' },
    { emoji: '🥬', description: 'Leafy Green' },
    { emoji: '🥦', description: 'Broccoli' },
    { emoji: '🧄', description: 'Garlic' },
    { emoji: '🧅', description: 'Onion' },
    { emoji: '🍄', description: 'Mushroom' },
    { emoji: '🥭', description: 'Mango' },
    { emoji: '🧀', description: 'Cheese Wedge' },
    { emoji: '🍖', description: 'Meat on Bone' },
    { emoji: '🍗', description: 'Poultry Leg' },
    { emoji: '🥩', description: 'Cut of Meat' },
    { emoji: '🥓', description: 'Bacon' },
    { emoji: '🍔', description: 'Hamburger' },
    { emoji: '🍟', description: 'French Fries' },
    { emoji: '🌭', description: 'Hot Dog' },
    { emoji: '🍕', description: 'Pizza' },
    { emoji: '🥪', description: 'Sandwich' },
    { emoji: '🌮', description: 'Taco' },
    { emoji: '🌯', description: 'Burrito' },
    { emoji: '🥙', description: 'Stuffed Flatbread' },
    { emoji: '🍝', description: 'Spaghetti' },
    { emoji: '🍜', description: 'Steaming Bowl' },
    { emoji: '🍲', description: 'Pot of Food' },
    { emoji: '🥘', description: 'Shallow Pan of Food' },
    { emoji: '🍣', description: 'Sushi' },
    { emoji: '🍤', description: 'Shrimp' },
    { emoji: '🍱', description: 'Bento Box' },
    { emoji: '🍚', description: 'Cooked Rice' },
    { emoji: '🍙', description: 'Rice Ball' },
    { emoji: '🍘', description: 'Rice Cracker' },
    { emoji: '🥮', description: 'Moon Cake' },
    { emoji: '🍥', description: 'Fish Cake with Swirl' },
    { emoji: '🎂', description: 'Birthday Cake' },
    { emoji: '🍰', description: 'Shortcake' },
    { emoji: '🧁', description: 'Cupcake' },
    { emoji: '🍦', description: 'Soft Ice Cream' },
    { emoji: '🍨', description: 'Ice Cream' },
    { emoji: '🍧', description: 'Shaved Ice' },
    { emoji: '🧊', description: 'Ice Cube' },
    { emoji: '🥤', description: 'Cup with Straw' },
    { emoji: '🍹', description: 'Tropical Drink' },
    { emoji: '🍸', description: 'Cocktail Glass' },
    { emoji: '🍷', description: 'Wine Glass' },
    { emoji: '🍺', description: 'Beer Mug' },
    { emoji: '🍻', description: 'Clinking Beer Mugs' },
    { emoji: '🥂', description: 'Clinking Glasses' },
    { emoji: '🥃', description: 'Tumbler Glass' },
    { emoji: '🧃', description: 'Juice Box' },
    { emoji: '🧉', description: 'Mate' },
    { emoji: '☕', description: 'Hot Beverage' },
    { emoji: '🥛', description: 'Glass of Milk' },
    { emoji: '🧊', description: 'Ice Cube' },
    { emoji: '🥤', description: 'Cup with Straw' },
    { emoji: '💧', description: 'Droplet' },
    { emoji: '🍶', description: 'Sake Bottle and Cup' },
    { emoji: '🥢', description: 'Chopsticks' },
    { emoji: '🍽️', description: 'Fork and Knife with Plate' },
    { emoji: '🍴', description: 'Fork and Knife' },
    { emoji: '🍕', description: 'Pizza' },
    { emoji: '🍔', description: 'Hamburger' },
    { emoji: '🍟', description: 'French Fries' },
    { emoji: '🌭', description: 'Hot Dog' },
    { emoji: '🍖', description: 'Meat on Bone' },
    { emoji: '🍗', description: 'Poultry Leg' },
    { emoji: '🥩', description: 'Cut of Meat' },
    { emoji: '🍥', description: 'Fish Cake with Swirl' },
    { emoji: '🥮', description: 'Moon Cake' },
    { emoji: '🍩', description: 'Doughnut' },
    { emoji: '🍪', description: 'Cookie' },
    { emoji: '🍫', description: 'Chocolate Bar' },
    { emoji: '🍬', description: 'Candy' },
    { emoji: '🍭', description: 'Lollipop' },
    { emoji: '🧁', description: 'Cupcake' },
    { emoji: '🎂', description: 'Birthday Cake' },
    { emoji: '🍰', description: 'Shortcake' },
    { emoji: '🍮', description: 'Custard' },
    { emoji: '🍨', description: 'Ice Cream' },
    { emoji: '🍧', description: 'Shaved Ice' },
    { emoji: '🥥', description: 'Coconut' },
    { emoji: '🥝', description: 'Kiwi Fruit' },
    { emoji: '🍉', description: 'Watermelon' },
    { emoji: '🍇', description: 'Grapes' },
    { emoji: '🍒', description: 'Cherries' },
    { emoji: '🍑', description: 'Peach' },
    { emoji: '🍍', description: 'Pineapple' },
    { emoji: '🥭', description: 'Mango' },
    { emoji: '🍊', description: 'Tangerine' },
    { emoji: '🍋', description: 'Lemon' },
    { emoji: '🍏', description: 'Green Apple' },
    { emoji: '🍎', description: 'Red Apple' },
    { emoji: '🍐', description: 'Pear' },
    { emoji: '🍅', description: 'Tomato' },
    { emoji: '🥕', description: 'Carrot' },
    { emoji: '🌽', description: 'Ear of Corn' },
    { emoji: '🌶️', description: 'Hot Pepper' },
    { emoji: '🥬', description: 'Leafy Green' },
    { emoji: '🥦', description: 'Broccoli' },
    { emoji: '🍄', description: 'Mushroom' },
    { emoji: '🌰', description: 'Chestnut' },
    { emoji: '🥜', description: 'Peanuts' },
    { emoji: '🌾', description: 'Sheaf of Rice' },
    { emoji: '🍞', description: 'Loaf of Bread' },
    { emoji: '🥖', description: 'Baguette Bread' },
    { emoji: '🥯', description: 'Bagel' },
    { emoji: '🥨', description: 'Pretzel' },
    { emoji: '🍕', description: 'Pizza' },
    { emoji: '🍔', description: 'Hamburger' },
    { emoji: '🌭', description: 'Hot Dog' },
  ];
  
const FoodAndDrink:React.FC=()=> {
  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '10px' }}>
        {emojiList.map((item, index) => (
          <div key={index} className="emoji-card p-4 border rounded text-center bg-light hover-effect">
            <div  style={{ display:'flex', alignItems: 'flex-end', height:'15px', width:'15px'  }}>
              <img src="/bookmark.png" alt="" />
            </div>
            <div className="emoji" style={{ fontSize: '2rem' }}>{item.emoji}</div>
            <div className="description mt-2">{item.description}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
export default FoodAndDrink;