import React from 'react';
const emojiList = [
    { emoji: '👶', description: 'Baby' },
    { emoji: '👦', description: 'Boy' },
    { emoji: '👧', description: 'Girl' },
    { emoji: '🧒', description: 'Child' },
    { emoji: '👨', description: 'Man' },
    { emoji: '👩', description: 'Woman' },
    { emoji: '🧑', description: 'Person' },
    { emoji: '👵', description: 'Old Woman' },
    { emoji: '👴', description: 'Old Man' },
    { emoji: '👲', description: 'Man with Chinese Cap' },
    { emoji: '👳‍♂️', description: 'Man with Turban' },
    { emoji: '👳‍♀️', description: 'Woman with Turban' },
    { emoji: '🧕', description: 'Woman with Headscarf' },
    { emoji: '🧔', description: 'Bearded Person' },
    { emoji: '👨‍🦰', description: 'Man with Curly Red Hair' },
    { emoji: '👩‍🦰', description: 'Woman with Curly Red Hair' },
    { emoji: '👨‍🦳', description: 'Man with Curly White Hair' },
    { emoji: '👩‍🦳', description: 'Woman with Curly White Hair' },
    { emoji: '👨‍🦲', description: 'Man with Bald Head' },
    { emoji: '👩‍🦲', description: 'Woman with Bald Head' },
    { emoji: '🧑‍🦰', description: 'Person with Curly Red Hair' },
    { emoji: '🧑‍🦳', description: 'Person with Curly White Hair' },
    { emoji: '🧑‍🦲', description: 'Person with Bald Head' },
    { emoji: '👩‍⚕️', description: 'Woman Health Worker' },
    { emoji: '👨‍⚕️', description: 'Man Health Worker' },
    { emoji: '🧑‍⚕️', description: 'Person Health Worker' },
    { emoji: '👩‍🍳', description: 'Woman Cook' },
    { emoji: '👨‍🍳', description: 'Man Cook' },
    { emoji: '🧑‍🍳', description: 'Person Cook' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍🌾', description: 'Woman Farmer' },
    { emoji: '👨‍🌾', description: 'Man Farmer' },
    { emoji: '🧑‍🌾', description: 'Person Farmer' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Office Worker' },
    { emoji: '👨‍💼', description: 'Man Office Worker' },
    { emoji: '🧑‍💼', description: 'Person Office Worker' },
    { emoji: '🧑‍🎤', description: 'Person Artist' },
    { emoji: '🧑‍⚕️', description: 'Person Health Worker' },
    { emoji: '👩‍💻', description: 'Woman Technologist' },
    { emoji: '👨‍💻', description: 'Man Technologist' },
    { emoji: '🧑‍💻', description: 'Person Technologist' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '🧑‍💼', description: 'Person Office Worker' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Business Person' },
    { emoji: '👨‍💼', description: 'Man Business Person' },
    { emoji: '🧑‍💼', description: 'Person Business Person' },
    { emoji: '👩‍💻', description: 'Woman Programmer' },
    { emoji: '👨‍💻', description: 'Man Programmer' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Business Person' },
    { emoji: '👨‍💼', description: 'Man Business Person' },
    { emoji: '🧑‍💼', description: 'Person Business Person' },
    { emoji: '👩‍💻', description: 'Woman Programmer' },
    { emoji: '👨‍💻', description: 'Man Programmer' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Business Person' },
    { emoji: '👨‍💼', description: 'Man Business Person' },
    { emoji: '🧑‍💼', description: 'Person Business Person' },
    { emoji: '👩‍💻', description: 'Woman Programmer' },
    { emoji: '👨‍💻', description: 'Man Programmer' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Business Person' },
    { emoji: '👨‍💼', description: 'Man Business Person' },
    { emoji: '🧑‍💼', description: 'Person Business Person' },
    { emoji: '👩‍💻', description: 'Woman Programmer' },
    { emoji: '👨‍💻', description: 'Man Programmer' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' },
    { emoji: '👩‍⚖️', description: 'Woman Judge' },
    { emoji: '👨‍⚖️', description: 'Man Judge' },
    { emoji: '🧑‍⚖️', description: 'Person Judge' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍💼', description: 'Woman Business Person' },
    { emoji: '👨‍💼', description: 'Man Business Person' },
    { emoji: '🧑‍💼', description: 'Person Business Person' },
    { emoji: '👩‍💻', description: 'Woman Programmer' },
    { emoji: '👨‍💻', description: 'Man Programmer' },
    { emoji: '🧑‍💻', description: 'Person Programmer' },
    { emoji: '👩‍🏫', description: 'Woman Teacher' },
    { emoji: '👨‍🏫', description: 'Man Teacher' },
    { emoji: '🧑‍🏫', description: 'Person Teacher' },
    { emoji: '👩‍🎨', description: 'Woman Artist' },
    { emoji: '👨‍🎨', description: 'Man Artist' },
    { emoji: '🧑‍🎨', description: 'Person Artist' },
    { emoji: '👩‍🎤', description: 'Woman Singer' },
    { emoji: '👨‍🎤', description: 'Man Singer' },
    { emoji: '🧑‍🎤', description: 'Person Singer' },
    { emoji: '👩‍🍳', description: 'Woman Chef' },
    { emoji: '👨‍🍳', description: 'Man Chef' },
    { emoji: '🧑‍🍳', description: 'Person Chef' },
    { emoji: '👩‍🔧', description: 'Woman Mechanic' },
    { emoji: '👨‍🔧', description: 'Man Mechanic' },
    { emoji: '🧑‍🔧', description: 'Person Mechanic' },
    { emoji: '👩‍🏭', description: 'Woman Factory Worker' },
    { emoji: '👨‍🏭', description: 'Man Factory Worker' },
    { emoji: '🧑‍🏭', description: 'Person Factory Worker' },
    { emoji: '👩‍🔬', description: 'Woman Scientist' },
    { emoji: '👨‍🔬', description: 'Man Scientist' },
    { emoji: '🧑‍🔬', description: 'Person Scientist' },
    { emoji: '👩‍⚕️', description: 'Woman Doctor' },
    { emoji: '👨‍⚕️', description: 'Man Doctor' },
    { emoji: '🧑‍⚕️', description: 'Person Doctor' },
    { emoji: '👩‍🎓', description: 'Woman Graduate' },
    { emoji: '👨‍🎓', description: 'Man Graduate' },
    { emoji: '🧑‍🎓', description: 'Person Graduate' },
    { emoji: '👩‍✈️', description: 'Woman Pilot' },
    { emoji: '👨‍✈️', description: 'Man Pilot' },
    { emoji: '🧑‍✈️', description: 'Person Pilot' },
    { emoji: '👩‍🚀', description: 'Woman Astronaut' },
    { emoji: '👨‍🚀', description: 'Man Astronaut' },
    { emoji: '🧑‍🚀', description: 'Person Astronaut' },
    { emoji: '👩‍🚒', description: 'Woman Firefighter' },
    { emoji: '👨‍🚒', description: 'Man Firefighter' },
    { emoji: '🧑‍🚒', description: 'Person Firefighter' }
  ];

const PeopleAndBody: React.FC = () => {
  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '10px' }}>
        {emojiList.map((item, index) => (
          <div key={index} className="emoji-card p-4 border rounded text-center bg-light hover-effect">
            <div  style={{ display:'flex', alignItems: 'flex-end', height:'15px', width:'15px'  }}>
              <img src="/bookmark.png" alt="" />
            </div>
            <div className="emoji" style={{ fontSize: '2rem' }}>{item.emoji}</div>
            <div className="description mt-2">{item.description}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default PeopleAndBody;
