import React from 'react'
const emojiList = [
    { emoji: '🏖️', description: 'Beach with Umbrella' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏕️', description: 'Camping' },
    { emoji: '🏠', description: 'House' },
    { emoji: '🏰', description: 'Castle' },
    { emoji: '🏯', description: 'Japanese Castle' },
    { emoji: '🏛️', description: 'Classical Building' },
    { emoji: '🕌', description: 'Mosque' },
    { emoji: '🕍', description: 'Synagogue' },
    { emoji: '⛩️', description: 'Shinto Shrine' },
    { emoji: '🗼', description: 'Tokyo Tower' },
    { emoji: '🗽', description: 'Statue of Liberty' },
    { emoji: '🏟️', description: 'Stadium' },
    { emoji: '🏛️', description: 'Museum' },
    { emoji: '🏗️', description: 'Building Construction' },
    { emoji: '🕌', description: 'Mosque' },
    { emoji: '🗺️', description: 'World Map' },
    { emoji: '🌍', description: 'Earth Globe Europe-Africa' },
    { emoji: '🌎', description: 'Earth Globe Americas' },
    { emoji: '🌏', description: 'Earth Globe Asia-Australia' },
    { emoji: '🧳', description: 'Luggage' },
    { emoji: '🚉', description: 'Railway Station' },
    { emoji: '🚢', description: 'Ship' },
    { emoji: '✈️', description: 'Airplane' },
    { emoji: '🚀', description: 'Rocket' },
    { emoji: '🚁', description: 'Helicopter' },
    { emoji: '🚕', description: 'Taxi' },
    { emoji: '🚗', description: 'Car' },
    { emoji: '🚙', description: 'Recreational Vehicle' },
    { emoji: '🚌', description: 'Bus' },
    { emoji: '🚎', description: 'Trolleybus' },
    { emoji: '🛴', description: 'Kick Scooter' },
    { emoji: '🚲', description: 'Bicycle' },
    { emoji: '🛳️', description: 'Cruise Ship' },
    { emoji: '🦙', description: 'Llama' },
    { emoji: '🦒', description: 'Giraffe' },
    { emoji: '🦓', description: 'Zebra' },
    { emoji: '🦘', description: 'Kangaroo' },
    { emoji: '🐎', description: 'Horse' },
    { emoji: '🦙', description: 'Llama' },
    { emoji: '🦏', description: 'Rhinoceros' },
    { emoji: '🦒', description: 'Giraffe' },
    { emoji: '🐒', description: 'Monkey' },
    { emoji: '🐊', description: 'Crocodile' },
    { emoji: '🐍', description: 'Snake' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🌄', description: 'Sunrise Over Mountains' },
    { emoji: '🌠', description: 'Shooting Star' },
    { emoji: '🏖️', description: 'Beach with Umbrella' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏜️', description: 'Desert' },
    { emoji: '🏔️', description: 'Snow-Capped Mountain' },
    { emoji: '⛰️', description: 'Mountain' },
    { emoji: '🌋', description: 'Volcano' },
    { emoji: '🗻', description: 'Mount Fuji' },
    { emoji: '🛤️', description: 'Railway Track' },
    { emoji: '🚦', description: 'Traffic Light' },
    { emoji: '🚧', description: 'Construction' },
    { emoji: '⛽', description: 'Fuel Pump' },
    { emoji: '🛣️', description: 'Motorway' },
    { emoji: '🏡', description: 'House with Garden' },
    { emoji: '🏢', description: 'Office Building' },
    { emoji: '🏬', description: 'Department Store' },
    { emoji: '🏥', description: 'Hospital' },
    { emoji: '🏤', description: 'Post Office' },
    { emoji: '🏦', description: 'Bank' },
    { emoji: '🏨', description: 'Hotel' },
    { emoji: '🏪', description: 'Convenience Store' },
    { emoji: '🏭', description: 'Factory' },
    { emoji: '🛋️', description: 'Couch and Lamp' },
    { emoji: '🏡', description: 'House with Garden' },
    { emoji: '🌇', description: 'Sunset Over Buildings' },
    { emoji: '🌆', description: 'Cityscape at Dusk' },
    { emoji: '🌃', description: 'Night with Stars' },
    { emoji: '🏙️', description: 'Cityscape' },
    { emoji: '🏢', description: 'Office Building' },
    { emoji: '🏬', description: 'Department Store' },
    { emoji: '🏣', description: 'Japanese Post Office' },
    { emoji: '🏦', description: 'Bank' },
    { emoji: '🏩', description: 'Love Hotel' },
    { emoji: '🏥', description: 'Hospital' },
    { emoji: '🛖', description: 'Hut' },
    { emoji: '🏘️', description: 'Houses' },
    { emoji: '🏙️', description: 'Cityscape' },
    { emoji: '🌇', description: 'Sunset Over Buildings' },
    { emoji: '🏔️', description: 'Snow-Capped Mountain' },
    { emoji: '⛰️', description: 'Mountain' },
    { emoji: '🌋', description: 'Volcano' },
    { emoji: '🗻', description: 'Mount Fuji' },
    { emoji: '🛤️', description: 'Railway Track' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏜️', description: 'Desert' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🌄', description: 'Sunrise Over Mountains' },
    { emoji: '🌠', description: 'Shooting Star' },
    { emoji: '🌌', description: 'Milky Way' },
    { emoji: '🌈', description: 'Rainbow' },
    { emoji: '🚲', description: 'Bicycle' },
    { emoji: '🛶', description: 'Canoe' },
    { emoji: '⛵', description: 'Sailboat' },
    { emoji: '🚤', description: 'Speedboat' },
    { emoji: '🏊', description: 'Person Swimming' },
    { emoji: '🏄', description: 'Person Surfing' },
    { emoji: '🏋️', description: 'Person Lifting Weights' },
    { emoji: '🏌️', description: 'Person Golfing' },
    { emoji: '🚴', description: 'Person Biking' },
    { emoji: '🚵', description: 'Person Mountain Biking' },
    { emoji: '🧗', description: 'Person Climbing' },
    { emoji: '🏊‍♂️', description: 'Man Swimming' },
    { emoji: '🏊‍♀️', description: 'Woman Swimming' },
    { emoji: '🏄‍♂️', description: 'Man Surfing' },
    { emoji: '🏄‍♀️', description: 'Woman Surfing' },
    { emoji: '🏋️‍♂️', description: 'Man Lifting Weights' },
    { emoji: '🏋️‍♀️', description: 'Woman Lifting Weights' },
    { emoji: '🏌️‍♂️', description: 'Man Golfing' },
    { emoji: '🏌️‍♀️', description: 'Woman Golfing' },
    { emoji: '🚴‍♂️', description: 'Man Biking' },
    { emoji: '🚴‍♀️', description: 'Woman Biking' },
    { emoji: '🚵‍♂️', description: 'Man Mountain Biking' },
    { emoji: '🚵‍♀️', description: 'Woman Mountain Biking' },
    { emoji: '🧗‍♂️', description: 'Man Climbing' },
    { emoji: '🧗‍♀️', description: 'Woman Climbing' },
    { emoji: '🏖️', description: 'Beach with Umbrella' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏜️', description: 'Desert' },
    { emoji: '🏔️', description: 'Snow-Capped Mountain' },
    { emoji: '⛰️', description: 'Mountain' },
    { emoji: '🌋', description: 'Volcano' },
    { emoji: '🗻', description: 'Mount Fuji' },
    { emoji: '🚦', description: 'Traffic Light' },
    { emoji: '🚧', description: 'Construction' },
    { emoji: '⛽', description: 'Fuel Pump' },
    { emoji: '🛣️', description: 'Motorway' },
    { emoji: '🌍', description: 'Earth Globe Europe-Africa' },
    { emoji: '🌎', description: 'Earth Globe Americas' },
    { emoji: '🌏', description: 'Earth Globe Asia-Australia' },
    { emoji: '🧳', description: 'Luggage' },
    { emoji: '🚉', description: 'Railway Station' },
    { emoji: '🚢', description: 'Ship' },
    { emoji: '✈️', description: 'Airplane' },
    { emoji: '🚀', description: 'Rocket' },
    { emoji: '🚁', description: 'Helicopter' },
    { emoji: '🚕', description: 'Taxi' },
    { emoji: '🚗', description: 'Car' },
    { emoji: '🚙', description: 'Recreational Vehicle' },
    { emoji: '🚌', description: 'Bus' },
    { emoji: '🚎', description: 'Trolleybus' },
    { emoji: '🛴', description: 'Kick Scooter' },
    { emoji: '🚲', description: 'Bicycle' },
    { emoji: '🛳️', description: 'Cruise Ship' },
    { emoji: '🦙', description: 'Llama' },
    { emoji: '🦒', description: 'Giraffe' },
    { emoji: '🦓', description: 'Zebra' },
    { emoji: '🦘', description: 'Kangaroo' },
    { emoji: '🐎', description: 'Horse' },
    { emoji: '🦙', description: 'Llama' },
    { emoji: '🦏', description: 'Rhinoceros' },
    { emoji: '🦒', description: 'Giraffe' },
    { emoji: '🐒', description: 'Monkey' },
    { emoji: '🐊', description: 'Crocodile' },
    { emoji: '🐍', description: 'Snake' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🌄', description: 'Sunrise Over Mountains' },
    { emoji: '🌠', description: 'Shooting Star' },
    { emoji: '🏖️', description: 'Beach with Umbrella' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏜️', description: 'Desert' },
    { emoji: '🏔️', description: 'Snow-Capped Mountain' },
    { emoji: '⛰️', description: 'Mountain' },
    { emoji: '🌋', description: 'Volcano' },
    { emoji: '🗻', description: 'Mount Fuji' },
    { emoji: '🛤️', description: 'Railway Track' },
    { emoji: '🚦', description: 'Traffic Light' },
    { emoji: '🚧', description: 'Construction' },
    { emoji: '⛽', description: 'Fuel Pump' },
    { emoji: '🛣️', description: 'Motorway' },
    { emoji: '🏡', description: 'House with Garden' },
    { emoji: '🏢', description: 'Office Building' },
    { emoji: '🏬', description: 'Department Store' },
    { emoji: '🏥', description: 'Hospital' },
    { emoji: '🏤', description: 'Post Office' },
    { emoji: '🏦', description: 'Bank' },
    { emoji: '🏨', description: 'Hotel' },
    { emoji: '🏪', description: 'Convenience Store' },
    { emoji: '🏭', description: 'Factory' },
    { emoji: '🛋️', description: 'Couch and Lamp' },
    { emoji: '🏡', description: 'House with Garden' },
    { emoji: '🌇', description: 'Sunset Over Buildings' },
    { emoji: '🌆', description: 'Cityscape at Dusk' },
    { emoji: '🌃', description: 'Night with Stars' },
    { emoji: '🏙️', description: 'Cityscape' },
    { emoji: '🏢', description: 'Office Building' },
    { emoji: '🏬', description: 'Department Store' },
    { emoji: '🏣', description: 'Japanese Post Office' },
    { emoji: '🏦', description: 'Bank' },
    { emoji: '🏩', description: 'Love Hotel' },
    { emoji: '🏥', description: 'Hospital' },
    { emoji: '🛖', description: 'Hut' },
    { emoji: '🏘️', description: 'Houses' },
    { emoji: '🏙️', description: 'Cityscape' },
    { emoji: '🌇', description: 'Sunset Over Buildings' },
    { emoji: '🏔️', description: 'Snow-Capped Mountain' },
    { emoji: '⛰️', description: 'Mountain' },
    { emoji: '🌋', description: 'Volcano' },
    { emoji: '🗻', description: 'Mount Fuji' },
    { emoji: '🛤️', description: 'Railway Track' },
    { emoji: '🏞️', description: 'National Park' },
    { emoji: '🏜️', description: 'Desert' },
    { emoji: '🏝️', description: 'Desert Island' },
    { emoji: '🌅', description: 'Sunrise' },
    { emoji: '🌄', description: 'Sunrise Over Mountains' },
    { emoji: '🌠', description: 'Shooting Star' },
    { emoji: '🌌', description: 'Milky Way' },
    { emoji: '🌈', description: 'Rainbow' },
    { emoji: '🚲', description: 'Bicycle' },
    { emoji: '🛶', description: 'Canoe' },
    { emoji: '⛵', description: 'Sailboat' },
    { emoji: '🚤', description: 'Speedboat' },
    { emoji: '🏊', description: 'Person Swimming' },
    { emoji: '🏄', description: 'Person Surfing' },
    { emoji: '🏋️', description: 'Person Lifting Weights' },
    { emoji: '🏌️', description: 'Person Golfing' },
    { emoji: '🚴', description: 'Person Biking' },
    { emoji: '🚵', description: 'Person Mountain Biking' },
    { emoji: '🧗', description: 'Person Climbing' },
    { emoji: '🏊‍♂️', description: 'Man Swimming' },
    { emoji: '🏊‍♀️', description: 'Woman Swimming' },
    { emoji: '🏄‍♂️', description: 'Man Surfing' },
    { emoji: '🏄‍♀️', description: 'Woman Surfing' },
    { emoji: '🏋️‍♂️', description: 'Man Lifting Weights' },
    { emoji: '🏋️‍♀️', description: 'Woman Lifting Weights' },
    { emoji: '🏌️‍♂️', description: 'Man Golfing' },
    { emoji: '🏌️‍♀️', description: 'Woman Golfing' },
    { emoji: '🚴‍♂️', description: 'Man Biking' },
    { emoji: '🚴‍♀️', description: 'Woman Biking' },
    { emoji: '🚵‍♂️', description: 'Man Mountain Biking' },
    { emoji: '🚵‍♀️', description: 'Woman Mountain Biking' },
    { emoji: '🧗‍♂️', description: 'Man Climbing' },
    { emoji: '🧗‍♀️', description: 'Woman Climbing' }
  ];
  
const TravelAndPlaces:React.FC=()=> {
  return (
    <div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '10px' }}>
        {emojiList.map((item, index) => (
          <div key={index} className="emoji-card p-4 border rounded text-center bg-light hover-effect">
            <div  style={{ display:'flex', alignItems: 'flex-end', height:'15px', width:'15px'  }}>
              <img src="/bookmark.png" alt="" />
            </div>
            <div className="emoji" style={{ fontSize: '2rem' }}>{item.emoji}</div>
            <div className="description mt-2">{item.description}</div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default TravelAndPlaces;
